# Open Data

```{r open-data}
# install.packages("taylor")
# library(taylor)
# library(dplyr)
# data(package = "taylor")

# Eras Tour Suprise
head(eras_tour_surprise)
colnames(eras_tour_surprise)
dim(eras_tour_surprise)

# Songs
head(taylor_album_songs)
colnames(taylor_album_songs)
dim(taylor_album_songs)

# Albums and EPS
head(taylor_albums)
colnames(taylor_albums)

# All Songs
head(taylor_all_songs)
colnames(taylor_all_songs)

```


# External Data Source

```{r}
external_data = read.csv("data/billboard_charts.csv")
```

# Merge Data 


```{r}
merged_data = merge(external_data, taylor_all_songs, by = "track_name", 
                    all.y = TRUE)
```

```{r}
# check that there are 230 tack names that are the same
track_names_df1 <- external_data$track_name
track_names_df2 <- taylor_all_songs$track_name
common_tracks <- intersect(track_names_df1, track_names_df2)
num_common_tracks <- length(common_tracks)
print(num_common_tracks)
```


```{r}
# make wks_on_chart 0 if no week reocrded
merged_data$wks_on_chart[is.na(merged_data$wks_on_chart)] = 0
# check
sum(merged_data$wks_on_chart == 0) == 95
```


# Full Data Frame

```{r}
# load
lyrics_df = read.csv("data/lyrics.csv")
audio_df = read.csv("data/audio.csv")

# take just cluster and make factor for lyrics
lyrics_df <- subset(lyrics_df, select = c(track_name, cluster_assignment))
lyrics_df$lyric_cluster = as.factor(lyrics_df$cluster_assignment)
lyrics_df <- subset(lyrics_df, select = -cluster_assignment)

# take just cluster and make factor for audio
audio_df <- subset(audio_df, select = c(track_name, cluster_assignment))
audio_df$audio_cluster = as.factor(audio_df$cluster_assignment)
audio_df <- subset(audio_df, select = -cluster_assignment)

# merge data frames
full = merge(merged_data, lyrics_df, by = "track_name", 
                    all.y = TRUE)
full = merge(full, audio_df, by = "track_name", all.y = TRUE)

# make no album a category instead of na and make it a factor
full$album_name[is.na(full$album_name)] = "no_album"
full$album_name = as.factor(full$album_name)

# call full model model_df for model below
model_df = full
```


# Poisson Regression 


## Lyrics Cluster Categories / Histograms 

```{r}
#library(ggplot2)
#library(gridExtra)
wks_range <- range(model_df$wks_on_chart, na.rm = TRUE)

# base line ggplot
mean_val = mean(model_df$wks_on_chart)
median_val = median(model_df$wks_on_chart)

baseline = ggplot(data = model_df, aes(x = wks_on_chart)) + 
  geom_histogram(binwidth = 1) +
  labs(title = "Baseline Wks On Chart") +
  scale_x_continuous(limits = wks_range) + 
  geom_vline(xintercept = mean_val, color="blue", linetype="dashed", size=1) +
  geom_vline(xintercept = median_val, color="red", linetype="dotted", size=1) 



hist_list <- list(baseline)
for (i in 0:13) {
  cluster_data <- subset(model_df, lyric_cluster == i)
  hist_list[[i + 2]] <- 
    ggplot(data = cluster_data, aes(x = wks_on_chart)) +
    geom_histogram(binwidth = 1) + 
    labs(title = paste("Hist", i)) +
    scale_x_continuous(limits = wks_range)

}

# plot
do.call(grid.arrange, c(hist_list, ncol = 5))
```

```{r}
library(ggplot2)

for (i in 0:13) {
  cluster_data <- subset(model_df, lyric_cluster == i)
  
  # Calculate the square root of 'wks_on_chart' since you're plotting that
  sqrt_wks_on_chart <- sqrt(cluster_data$wks_on_chart)
  
  # Calculate mean and median of the transformed data
  mean_val <- mean(sqrt_wks_on_chart, na.rm = TRUE)
  median_val <- median(sqrt_wks_on_chart, na.rm = TRUE)
  
  # Add the histograms to the list
  hist_list[[i + 2]] <- 
    ggplot(data = cluster_data, aes(x = sqrt(wks_on_chart))) +
    geom_histogram(binwidth = 1) + 
    geom_vline(xintercept = mean_val, color="blue", linetype="dashed", size=1) +
    geom_vline(xintercept = median_val, color="red", linetype="dotted", size=1) +
    labs(title = paste("Hist", i)) +
    scale_x_continuous(limits = wks_range) +
    theme_minimal() +
    labs(x = "Sqrt(Wks on Chart)", y = "Frequency") 
}


do.call(grid.arrange, c(hist_list, ncol = 5))
```

```{r}
# Assuming model_df is your original data frame
results_df <- data.frame(cluster = integer(), mean = numeric(), median = numeric(), size = numeric())

for (i in 0:13) {
  cluster_data <- subset(model_df, lyric_cluster == i)
  mean_val <- mean(cluster_data$wks_on_chart, na.rm = TRUE)
  median_val <- median(cluster_data$wks_on_chart, na.rm = TRUE)
  size = length(cluster_data$wks_on_chart)
  
  # Append the results for this cluster to the results dataframe
  results_df <- rbind(results_df, data.frame(cluster = i, mean = mean_val, median = median_val, size = size))
}

# baseline
results_df <- rbind(results_df, data.frame(cluster = "base" , mean = mean(model_df$wks_on_chart, na.rm = TRUE), median = median(model_df$wks_on_chart, na.rm = TRUE), size = size(model_df$wks_on_chart)))
# View the results
print(results_df)

# pop: 1, 6, 8, 10*, 12
# base: 2, 4, 5, 9, 11
# unpop: 0*, 3, 7, 13
```


```{r}
# recategorize lyric cluster
library(dplyr)

model_df <- model_df %>%
  mutate(lyric_cluster_pop_ = case_when(
    lyric_cluster %in% c(1, 6, 8, 10, 12) ~ 'more_pop',
    lyric_cluster %in% c(2, 4, 5, 9, 11) ~ 'base_pop',
    lyric_cluster %in% c(0, 3, 7, 13) ~ 'less_pop'
  ))

```

## Audio Cluster Categories / Histograms  

```{r}

hist_list_a <- list(baseline)
for (i in 0:14) {
  cluster_data <- subset(model_df, audio_cluster == i)
  hist_list_a[[i + 2]] <- 
    ggplot(data = cluster_data, aes(x = wks_on_chart)) +
    geom_histogram(binwidth = 1) + 
    labs(title = paste("Hist", i)) +
    scale_x_continuous(limits = wks_range) 

}


# plot
do.call(grid.arrange, c(hist_list_a, ncol = 4))

#pop: 1, 2, 3, 14
#base: 0, 4, 6, 7, 8, 10, 12
#unpop: 5, 9, 11, 13
```

```{r}
results_df_a <- data.frame(cluster = integer(), mean = numeric(), median = numeric(), size = numeric())

for (i in 0:14) {
  cluster_data <- subset(model_df, audio_cluster == i)
  mean_val <- mean(cluster_data$wks_on_chart, na.rm = TRUE)
  median_val <- median(cluster_data$wks_on_chart, na.rm = TRUE)
  size = length(cluster_data$wks_on_chart)
  
  # Append the results for this cluster to the results dataframe
  results_df_a <- rbind(results_df_a, data.frame(cluster = i, mean = mean_val, median = median_val, size = size))
}

# baseline
results_df_a <- rbind(results_df_a, data.frame(cluster = "base" , mean = mean(model_df$wks_on_chart, na.rm = TRUE), median = median(model_df$wks_on_chart, na.rm = TRUE), size = size(model_df$wks_on_chart)))
# View the results
print(results_df_a)

# pop: 1, 3, 8*, 14
# base: 4, 7, 11, 9, 12,
# unpop: 0, 2*, 5, 6, 10, 13, 
```


```{r}
# recategorize lyric cluster

model_df <- model_df %>%
  mutate(audio_cluster_pop_ = case_when(
    audio_cluster %in% c(1, 3, 8, 14) ~ 'more_pop',
    audio_cluster %in% c(4, 7, 11, 9, 12) ~ 'base_pop',
    audio_cluster %in% c(0, 2, 5, 6, 10, 13) ~ 'less_pop'
  ))

```

## Album Grouping + TV + Vault Variables

```{r}
albums = unique(model_df$album_name)

early = c("Taylor Swift", "Beautiful Eyes", "Fearless", 
          "Fearless (Taylor's Version)", "Speak Now", 
          "Speak Now (Taylor's Version)")
middle1 = c("Red", "Red (Taylor's Version)", "1989", "1989 (Taylor's Version)")
middle2 = c("reputation", "Lover")
later = c("folklore", "evermore", "Midnights")
misc = c("The Taylor Swift Holiday Collection", "no_album")
# check
(length(early) + length(middle1) + length(middle2) + length(later) + 
    length(misc)) == 17

# Add a new column to model_df with the album groupings
model_df <- model_df %>%
  mutate(album_group_ = case_when(
    album_name %in% early ~ "early",
    album_name %in% middle1 ~ "middle1",
    album_name %in% middle2 ~ "middle2",
    album_name %in% later ~ "later",
    album_name %in% misc ~ "misc"
  ))

model_df$album_group_ = as.factor(model_df$album_group_)
```


```{r}
# TV
model_df <- model_df %>%
  mutate(TV = grepl("\\(Taylor's Version\\)", track_name))
model_df

model_df
# from the vault 
model_df <- model_df %>%
  mutate(vault = grepl("\\[From The Vault\\]", track_name))
model_df


# check that the number of TV songs is 100
nrow(subset(model_df, TV == TRUE)) == 100

```

## Model 1 (popularity categorized cluster)

```{r}
#install.packages("MASS")
#library(MASS)
model <- glm(wks_on_chart ~ danceability + energy + speechiness + acousticness + 
               liveness + valence + tempo + lyric_cluster_pop_ + 
               audio_cluster_pop_ + album_group_ + TV + vault,
             data = model_df, family = poisson(link = "log"))
summary(model)
```


## Model 2 (original clusters)

```{r}
# model_df$audio_cluster <- relevel(model_df$audio_cluster, ref = "7")
# model_df$lyric_cluster <- relevel(model_df$lyric_cluster, ref = "4")
model_2 <- glm(wks_on_chart ~ danceability + energy + speechiness + acousticness + 
               liveness + valence + tempo  + 
               audio_cluster + lyric_cluster + album_group_ + TV + vault,
             data = model_df, family = poisson(link = "log"))
summary(model_2)
exp_coef2 <- exp(coef(model_2))
print(exp_coef2)
```
## Goodness of Fit 

```{r}
# Assume `model` is your fitted Poisson regression model
deviance_residuals <- residuals(model_2, type = "deviance")
plot(fitted(model_2), deviance_residuals, xlab = "Fitted Values", ylab = "Deviance Residuals")
abline(h = 0, col = "red")
# YJ said not that bad

```

# Visualization 

```{r}
ggplot(data = model_df, aes(x = album_release, y = wks_on_chart, color = audio_cluster_pop_)) + 
  geom_point() + 
  theme_minimal()
```

```{r}
model_df$sqrt_weeks_on_chart <- sqrt(model_df$wks_on_chart)

# Optional: Create explicit bins for the square root weeks on chart
# This is a step you might adjust depending on how you want your bins defined


library(ggplot2)

ggplot(model_df, aes(x = album_name, fill = audio_cluster_pop_)) +
  geom_bar(position = "fill") +  # This stacks the bar and scales it to fill 100% of the y-axis proportionally
  scale_y_continuous(labels = scales::percent) +  # Adjust y-axis to show percentage
  labs(title = "Histogram of Square Root of Weeks on Chart",
       x = "Square Root of Weeks on Chart (Binned)",
       y = "Proportion") +
  theme_minimal() +
  guides(fill = guide_legend(title = "Audio Cluster Pop")) + 
  theme_minimal() + 
  scale_fill_manual(values = c("more_pop" = "darkgreen", "base_pop" = "#339999", "less_pop" = "lightgreen")) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 


```

```{r}
ggplot(model_df, aes(x = sqrt_weeks_on_chart, fill = audio_cluster_pop_)) +
  geom_histogram(position = "stack", binwidth = 1) +  # This stacks the bar and scales it to fill 100% of the y-axis proportionally
  scale_y_continuous(labels = scales::percent) +  # Adjust y-axis to show percentage
  labs(title = "Histogram of Square Root of Weeks on Chart",
       x = "Square Root of Weeks on Chart (Binned)",
       y = "Proportion") +
  theme_minimal() +
  guides(fill = guide_legend(title = "Audio Cluster Pop")) + 
  theme_minimal()

```

