---
title: "LB"
output: html_document
date: "2024-03-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#("taylor")
library(taylor)
#data(package = "taylor")

#install.packages("compindexR")
library(compindexR)
library(dplyr)
library(stringr)
library(ggplot2)
library(cowplot)
```

## Different Data Sets

eras_tour_surprise  -->   The Eras Tour Surprise Songs
taylor_album_songs  -->   Data for Taylor Swift songs
taylor_albums  -->     Data for Taylor Swift's studio albums and EPs
taylor_all_songs  -->   Data for Taylor Swift songs

## Lyric cleaning logic
```{r}
df <- taylor_all_songs 
n <- nrow(df)

## Creating lyric dataframe 
lyric_matrix <- matrix(ncol = 2, nrow = n)

for (i in 1:n){
  
  ## Getting song name
  songName <- df[i, "track_name"]$track_name
  
  ## Getting lyrics
  temp <- as.data.frame(taylor_all_songs[i,"lyrics"]$lyrics)
  lyrics <- tolower(gsub("[^A-Za-z0-9 ]", "", paste(temp$lyric, collapse = " ")))
  
  ## Update lyric_df
  lyric_matrix[i, 1] = songName
  lyric_matrix[i, 2] = lyrics
}

## converting back to dataframe 
lyric_df <- as.data.frame(lyric_matrix)
colnames(lyric_df) <- c("track_name", "lyrics")
lyric_df

```
```{r}
taylor_all_songs
```

## Initial EDA
```{r}
## Notes: should add streams vs release plot, and streams vs some of these characteristics

hist_1 <- taylor_all_songs %>%
  ggplot(aes(x = danceability)) + geom_histogram(binwidth = 0.01, fill = "black", color = "white") +
             labs(title = "Histogram of Danceability Values", x = "Danceability Values", y = "Frequency")

hist_2 <- taylor_all_songs %>%
  ggplot(aes(x = energy)) + geom_histogram(binwidth = 0.01, fill = "black", color = "white") +
             labs(title = "Histogram of Energy Values", x = "Energy Values", y = "Frequency")

hist_3 <- taylor_all_songs %>%
  ggplot(aes(x = speechiness)) + geom_histogram(binwidth = 0.01, fill = "black", color = "white") +
             labs(title = "Histogram of Speechiness Values", x = "Speechiness Values", y = "Frequency")

hist_4 <- taylor_all_songs %>%
  ggplot(aes(x = liveness)) + geom_histogram(binwidth = 0.01, fill = "black", color = "white") +
             labs(title = "Histogram of Liveness Values", x = "Liveness Values", y = "Frequency")


hist_5 <- taylor_all_songs %>%
  ggplot(aes(x = valence)) + geom_histogram(binwidth = 0.01, fill = "black", color = "white") +
             labs(title = "Histogram of Valence Values", x = "Valence Values", y = "Frequency")

#hist_6 <- taylor_all_songs %>%
 # ggplot(aes(x = as.integer(track_release))) + geom_histogram(binwidth = 0.01, fill = "black", color = "white") +
  #           labs(title = "Histogram of Release Dates", x = "Release Dates", y = "Frequency")

plot_grid(hist_1, hist_2, hist_3, hist_4, hist_5, nrow = 3)


```









